version: '3.8'

services:
  database:
    image: mongo:4.2.10
    restart: always
    volumes:
      - ./mongod.conf:/etc/mongod.conf
      - ./mongodb:/data/db
    command: mongod --config /etc/mongod.conf
    env_file: app.env
    ports:
      - '27017:27017'
